name: Google Cloud Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    PROJECT_ID: your_project_id
    GCR_LOCATION: asia.gcr.io
    GKE_CLUSTER: your_cluster_name
    GKE_ZONE: asia-south1-a
    DEPLOYMENT_NAME:  your_deployment_name
    IMAGE: your_docker_image_name


jobs:
  Deployment:
    name: Deployment to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
         credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
          install_components: 'gke-gcloud-auth-plugin'

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker $GCR_LOCATION
    # - name: Set up GKE credentials
    #   run: |-
    #     gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Connect to Google Cluster
      uses: google-github-actions/get-gke-credentials@v0
      with:
         project_id: your_project_id
         cluster_name: your_cluster_name
         location: asia-south1-a

    - name: Datetime Tag for Docker Image
      id: datetime-git-tag
      run: echo "today=$(TZ=Asia/Calcutta date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Build
      run: |- 
         docker build --tag "$GCR_LOCATION/$PROJECT_ID/$IMAGE:${{ env.today }}" .
                
    - name: Push to Container Registry
      run:  
        docker push $GCR_LOCATION/$PROJECT_ID/$IMAGE:${{ env.today }}

    - name: Set up Kustomize
      working-directory: .github/kustomize/
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize 

    - name: Deploy to Gke
      working-directory: .github/kustomize/
      run: |-
        # replacing the image name in the k8s template 
        ./kustomize edit set image Location/PROJECT_ID/IMAGE:TAG=$GCR_LOCATION/$PROJECT_ID/$IMAGE:${{ env.today }}   
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide